hovermap:
  name: hovermap
  parent: base_link
  topic_name: audio
  position:
    x: 0
    y: 0
    z: 0.2
  orientation:
    r: 0
    p: 0
    y: 0
  rate: 1
respeaker:
  name: respeaker
  parent: base_link
  topic_name: audio
  position:
    x: 0
    y: 0
    z: 0.2
  orientation:
    r: 0
    p: 0
    y: 0
  rate: 1
realsense:
  name: camera_front
  parent: arch
  position:
    # CAD measurement taken relative to velodyne base_link frame
    x: ${0.038 + 0.13355}
    y: 0
    z: ${0.41 - 0.03585 - 0.27043}
  orientation:
    r: 0
    p: 0
    y: 0
  rate: 0
realsense_left:
  name: camera_left
  parent: arch
  position:
    # CAD measurement taken relative to velodyne base_link frame
    x: ${0.038 - 0.1505}
    y: 0.31595
    z: ${0.41 - 0.03585 - 0.27043}
  orientation:
    r: 0
    p: 0
    y: ${pi/2}
  rate: 0
realsense_right:
  name: camera_right
  parent: arch
  position:
    # CAD measurement taken relative to velodyne base_link frame
    x: ${0.038 - 0.1505}
    y: -0.31595
    z: ${0.41 - 0.03585 - 0.27043}
  orientation:
    r: 0
    p: 0
    y: ${-pi/2}
  rate: 0
realsense_rear:
  name: camera_rear
  parent: arch
  position:
    # CAD measurement taken relative to velodyne base_link frame
    x: ${0.038 - 0.466}
    y: 0.080
    z: ${0.41 - 0.03585 - 0.27043}
  orientation:
    r: 0
    p: 0
    y: ${pi}
  rate: 0
realsense_up:
  name: camera_up
  parent: arch
  position:
    # CAD measurement taken relative to velodyne base_link frame
    x: ${0.038 - 0.0905}
    y: 0.1588
    z: ${0.41 - 0.03585 - 0.030}
  orientation:
    r: 0
    p: ${-pi/2}
    y: 0
  rate: 0
realsense_t265_front:
  name: camera_t265_front
  parent: base_link
  position:
    x: 0.13
    y: -0.14
    z: 0.49
  orientation:
    r: 0
    p: 0.26179938779
    y: 0
  rate: 0
realsense_t265_right:
  name: camera_t265_right
  parent: base_link
  position:
    x: 0.0
    y: -0.32
    z: 0.27
  orientation:
    r: ${pi}
    p: 0.26179938779
    y: -1.57079633
  rate: 0
realsense_t265_left:
  name: camera_t265_left
  parent: base_link
  position:
    x: 0.0
    y: 0.32
    z: 0.27
  orientation:
    r: 0
    p: 0.26179938779
    y: 1.57079633
  rate: 0
boson:
  name: boson
  parent: arch
  position:
    x: 0.095
    y: 0.19
    z: 0.269
  orientation:
    r: 0
    p: -0.52359877559
    y: 0
  rate: 0
velodyne:
  name: velodyne
  parent: arch
  position:
    x: 0.038
    y: 0
    z: 0.41
  orientation:
    r: 0
    p: 0.0087266
    y: 0.78190754
  rate: 10
  topic_name: velodyne_points
velodyne_front:
  name: velodyne_front
  parent: arch
  position:
    x: 0.123
    y: 0
    z: 0.28
  orientation:
    r: -0.002618
    p: 0.41888
    y: -0.02618
  rate: 10
  topic_name: velodyne_front/velodyne_points
velodyne_rear:
  name: velodyne_rear
  parent: arch
  position:
    x: -0.48
    y: 0.02
    z: 0.233
  orientation:
    r: -0.05
    p: 0.45
    y: 3.07876 #${pi}
  rate: 10
  topic_name: velodyne_rear/velodyne_points
vn100:
  name: vn100
  parent: arch
  topic_name: vn100/imu
  position:
    x: 0
    y: 0.147
    z: 0.165
  orientation:
    r: 0
    p: 0
    y: 1.57079632679
  rate: 50

